pipeline {
    agent {
        node {
            label "Linux-Slave-01"
        }
    }
    stages {
        stage('task1') {
            steps {
                sh 'echo "Hello task1"'
            }
        }
        stage('task2') {
            steps {
                sh 'echo "Stack 2 !!!!"'
            }
        }
    }
}
